version: '2'

services:
  geocrafter:
    build: .
    container_name: hugo-geocrafter
    volumes:
      - ./hugo-site:/src
    ports:
      - 8001:8001
    command: hugo server --bind 0.0.0.0 -b https://geocrafter.eu/ -p 8001 -t geocrafter --config themes/geocrafter/config.toml --disableLiveReload=true --appendPort=false
    restart: always
