version: '2'

services:
  geocrafter:
    build: .
    container_name: hugo-geocrafter
    volumes:
      - ./hugo-site:/src
    ports:
      - 8001:8001
    command: hugo server --bind 0.0.0.0 -p 8001 -t geocrafter
    restart: always
