version: '3'

services:
  geocrafter-dev:
    build: .
    container_name: hugo-geocrafter
    volumes:
      - ./hugo-site:/src
    ports:
      - 8002:8002
    command: hugo server --bind 0.0.0.0 -p 8002 -t geocrafter --config themes/geocrafter/config.toml --disableLiveReload=true --appendPort=false
    restart: always

  geocrafter-prod:
    build: .
    container_name: hugo-geocrafter
    volumes:
      - ./hugo-site:/src
    ports:
      - 8001:8001
    command: hugo server --bind 0.0.0.0 -b https://geocrafter.eu/ -p 8001 -t geocrafter --config themes/geocrafter/config.toml --disableLiveReload=true --appendPort=false
    restart: always

  geocrafter-showcase:
    build:
      context: .
      dockerfile: Dockerfile.showcase
    container_name: hugo-geocrafter-showcase
    command: "hugo server --bind 0.0.0.0 -b https://labs.geocrafter.eu/ -p 8003 --themesDir=../.. --disableLiveReload=true --appendPort=false"
    ports:
      - "8003:8003"

  geocrafter-academy:
    build:
      context: .
      dockerfile: Dockerfile.academy
    container_name: hugo-geocrafter-academy
    command: "hugo server --bind 0.0.0.0 -b https://academy.geocrafter.eu/ -p 8004 --themesDir=../.. --disableLiveReload=true --appendPort=false"
    ports:
      - "8004:8004"

  geocrafter-karna:
    build:
      context: .
      dockerfile: Dockerfile.v2
    container_name: hugo-geocrafter-v2
    command: "hugo server --source='geocrafter/' --bind 0.0.0.0 -p 8005 --disableLiveReload=true --appendPort=false"
    ports:
      - "8005:8005"