# Site settings
baseurl = "https://geocrafter.eu/"
languageCode = "en-us"
title = "Geocrafter - Geospatial Studio"
theme = "geocrafter"


[params]

    # You can use Markdown syntax for urls [text](//url.to/source) for
    # most longer texts.

    # To provide some metadata for search engines feel free to add a few
    # information about you and your website.
    name = "Geocrafter - Geospatial Studio"
    description = "Geocrafter - Geospatial Studio, Unipessoal Lda."

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email youself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "info@geocrafter.eu"

    # Custom assets
	custom_css = []
	custom_js  = []

    [params.navigation]
        brand = "Geocrafter - Geospatial Studio"


    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "logo.svg"
        name = "Geocrafter - Geospatial Studio"
        subtitle = "We build your trust!"


    [params.portfolio]
        # All projects defined in their own files. You can find example projects
        # at 'exampleSite/data/projects'. Copy the 'projects' folder into the 'data' directory
        # at the root of this Hugo site.
        # For more informtion take a look at the README.
        title = "Craftfolio"

        [params.portfolio.modal]
            client = "Client"
            date = "Date"
            category = "Category"
            buttontext = "Close"


    [params.workshops]
        title = "Workshops"

        [params.workshops.modal]
            module = "Module"
            date = "Date"
            contents = "Contents"
            lenght = "Duration"
            price = "Price"
            buttontext = "Close"


    [params.about]
        title = "About Us"
        # The about text is splitted into a left and right column
        left = "<p align=\"justify\">We are a small innovative geospatial studio fostering the usage and development of Open Source based solutions.</p><p align=\"justify\">Our technical knowledge in geospatial world is built on top of two decades of experience both in public and private sectors.</p>"
        right = "<p align=\"justify\">We help organizations to achieve the best results using state of the art technology.</p><p align=\"justify\"> We provide a customized plan to excel your organization needs on geospatial world.</p><p>Don't hesitate and talk with us!</p>"

        [params.about.button]
            text = "Download theme"
            link = "//github.com/digitalcraftsman/hugo-freelancer-theme/archive/master.zip"
            icon = "download"


    [params.contact]
        title = "Contact Us"

        # 'error' defines error messages for invalid inputs
        [params.contact.form.name]
            text = "Name"
            error = "Please enter your name."

        [params.contact.form.email]
            text = "Email Address"
            error = "Please enter your email address."

        [params.contact.form.phone]
            text = "Phone Number"
            error = "Please enter your phone number."

        [params.contact.form.modules]
            text = "Módulo"
            error = "Please choose your subject."

        [params.contact.form.message]
            text = "Message"
            error = "Please enter a message."

        [params.contact.form.button]
            text = "Send"


    [params.footer]
        copyright = "Published under the Apache License 2.0. Crafted with <i class=\"fa fa-heart\"></i> by Geocrafter - Geospatial Studio. Powered by [Hugo](//gohugo.io)."

        [params.footer.location]
            title = "Office"
            # Postal address (add as many lines as necessary)
            address = ["HIESE - Quinta Vale do Espinhal", "EM 558-1 Vale do Espinhal", "3230-343 Penela", "PORTUGAL"]

        [params.footer.social]
            title = "Where to find us"
            # All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
            # for more icons. The icons are represented by their corresponding
            # CSS class.
            [[params.footer.social.networks]]
                icon = "fas fa-envelope"
                link = "mailto:info@geocrafter.eu"

            [[params.footer.social.networks]]
                icon = "fab fa-github"
                link = "//github.com/geocrafter-studio"

            [[params.footer.social.networks]]
                icon = "fab fa-linkedin"
                link = "//www.linkedin.com/company/geocrafter---geospatial-studio"

            [[params.footer.social.networks]]
                icon = "fab fa-twitter"
                link = "//twitter.com/GeocrafterGS"

            [[params.footer.social.networks]]
                icon = "fab fa-whatsapp"
                link = "//wa.me/351918336529"

        [params.footer.credits]
            title = "Get in Touch"
            text = "Our experts will provide you the best solution!"
